// Country names for the phone country picker, generated from Unicode CLDR
// (Node Intl.DisplayNames). Hermes has no Intl.DisplayNames, so they ship as data.
const COUNTRY_NAMES: Record<string, Record<string, string>> = {
 "en": {
  "AC": "Ascension Island",
  "AD": "Andorra",
  "AE": "United Arab Emirates",
  "AF": "Afghanistan",
  "AG": "Antigua & Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AO": "Angola",
  "AR": "Argentina",
  "AS": "American Samoa",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "Åland Islands",
  "AZ": "Azerbaijan",
  "BA": "Bosnia & Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgium",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "St. Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BQ": "Caribbean Netherlands",
  "BR": "Brazil",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "CA": "Canada",
  "CC": "Cocos (Keeling) Islands",
  "CD": "Congo - Kinshasa",
  "CF": "Central African Republic",
  "CG": "Congo - Brazzaville",
  "CH": "Switzerland",
  "CI": "Côte d’Ivoire",
  "CK": "Cook Islands",
  "CL": "Chile",
  "CM": "Cameroon",
  "CN": "China",
  "CO": "Colombia",
  "CR": "Costa Rica",
  "CU": "Cuba",
  "CV": "Cape Verde",
  "CW": "Curaçao",
  "CX": "Christmas Island",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "DE": "Germany",
  "DJ": "Djibouti",
  "DK": "Denmark",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "DZ": "Algeria",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egypt",
  "EH": "Western Sahara",
  "ER": "Eritrea",
  "ES": "Spain",
  "ET": "Ethiopia",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "Falkland Islands",
  "FM": "Micronesia",
  "FO": "Faroe Islands",
  "FR": "France",
  "GA": "Gabon",
  "GB": "United Kingdom",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "French Guiana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Greenland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Equatorial Guinea",
  "GR": "Greece",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HK": "Hong Kong SAR China",
  "HN": "Honduras",
  "HR": "Croatia",
  "HT": "Haiti",
  "HU": "Hungary",
  "ID": "Indonesia",
  "IE": "Ireland",
  "IL": "Israel",
  "IM": "Isle of Man",
  "IN": "India",
  "IO": "British Indian Ocean Territory",
  "IQ": "Iraq",
  "IR": "Iran",
  "IS": "Iceland",
  "IT": "Italy",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordan",
  "JP": "Japan",
  "KE": "Kenya",
  "KG": "Kyrgyzstan",
  "KH": "Cambodia",
  "KI": "Kiribati",
  "KM": "Comoros",
  "KN": "St. Kitts & Nevis",
  "KP": "North Korea",
  "KR": "South Korea",
  "KW": "Kuwait",
  "KY": "Cayman Islands",
  "KZ": "Kazakhstan",
  "LA": "Laos",
  "LB": "Lebanon",
  "LC": "St. Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LV": "Latvia",
  "LY": "Libya",
  "MA": "Morocco",
  "MC": "Monaco",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MF": "St. Martin",
  "MG": "Madagascar",
  "MH": "Marshall Islands",
  "MK": "North Macedonia",
  "ML": "Mali",
  "MM": "Myanmar (Burma)",
  "MN": "Mongolia",
  "MO": "Macao SAR China",
  "MP": "Northern Mariana Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldives",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Malaysia",
  "MZ": "Mozambique",
  "NA": "Namibia",
  "NC": "New Caledonia",
  "NE": "Niger",
  "NF": "Norfolk Island",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Netherlands",
  "NO": "Norway",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "New Zealand",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "French Polynesia",
  "PG": "Papua New Guinea",
  "PH": "Philippines",
  "PK": "Pakistan",
  "PL": "Poland",
  "PM": "St. Pierre & Miquelon",
  "PR": "Puerto Rico",
  "PS": "Palestinian Territories",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Romania",
  "RS": "Serbia",
  "RU": "Russia",
  "RW": "Rwanda",
  "SA": "Saudi Arabia",
  "SB": "Solomon Islands",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Sweden",
  "SG": "Singapore",
  "SH": "St. Helena",
  "SI": "Slovenia",
  "SJ": "Svalbard & Jan Mayen",
  "SK": "Slovakia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "South Sudan",
  "ST": "São Tomé & Príncipe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Syria",
  "SZ": "Eswatini",
  "TA": "Tristan da Cunha",
  "TC": "Turks & Caicos Islands",
  "TD": "Chad",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tajikistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Türkiye",
  "TT": "Trinidad & Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzania",
  "UA": "Ukraine",
  "UG": "Uganda",
  "US": "United States",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VA": "Vatican City",
  "VC": "St. Vincent & Grenadines",
  "VE": "Venezuela",
  "VG": "British Virgin Islands",
  "VI": "U.S. Virgin Islands",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "WF": "Wallis & Futuna",
  "WS": "Samoa",
  "XK": "Kosovo",
  "YE": "Yemen",
  "YT": "Mayotte",
  "ZA": "South Africa",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
 },
 "ar": {
  "AC": "جزيرة أسينشيون",
  "AD": "أندورا",
  "AE": "الإمارات العربية المتحدة",
  "AF": "أفغانستان",
  "AG": "أنتيغوا وبربودا",
  "AI": "أنغويلا",
  "AL": "ألبانيا",
  "AM": "أرمينيا",
  "AO": "أنغولا",
  "AR": "الأرجنتين",
  "AS": "ساموا الأمريكية",
  "AT": "النمسا",
  "AU": "أستراليا",
  "AW": "أروبا",
  "AX": "جزر آلاند",
  "AZ": "أذربيجان",
  "BA": "البوسنة والهرسك",
  "BB": "بربادوس",
  "BD": "بنغلاديش",
  "BE": "بلجيكا",
  "BF": "بوركينا فاسو",
  "BG": "بلغاريا",
  "BH": "البحرين",
  "BI": "بوروندي",
  "BJ": "بنين",
  "BL": "سان بارتليمي",
  "BM": "برمودا",
  "BN": "بروناي",
  "BO": "بوليفيا",
  "BQ": "هولندا الكاريبية",
  "BR": "البرازيل",
  "BS": "جزر البهاما",
  "BT": "بوتان",
  "BW": "بوتسوانا",
  "BY": "بيلاروس",
  "BZ": "بليز",
  "CA": "كندا",
  "CC": "جزر كوكوس (كيلينغ)",
  "CD": "الكونغو - كينشاسا",
  "CF": "جمهورية أفريقيا الوسطى",
  "CG": "الكونغو - برازافيل",
  "CH": "سويسرا",
  "CI": "ساحل العاج",
  "CK": "جزر كوك",
  "CL": "تشيلي",
  "CM": "الكاميرون",
  "CN": "الصين",
  "CO": "كولومبيا",
  "CR": "كوستاريكا",
  "CU": "كوبا",
  "CV": "الرأس الأخضر",
  "CW": "كوراساو",
  "CX": "جزيرة كريسماس",
  "CY": "قبرص",
  "CZ": "التشيك",
  "DE": "ألمانيا",
  "DJ": "جيبوتي",
  "DK": "الدانمرك",
  "DM": "دومينيكا",
  "DO": "جمهورية الدومينيكان",
  "DZ": "الجزائر",
  "EC": "الإكوادور",
  "EE": "إستونيا",
  "EG": "مصر",
  "EH": "الصحراء الغربية",
  "ER": "إريتريا",
  "ES": "إسبانيا",
  "ET": "إثيوبيا",
  "FI": "فنلندا",
  "FJ": "فيجي",
  "FK": "جزر فوكلاند",
  "FM": "ميكرونيزيا",
  "FO": "جزر فارو",
  "FR": "فرنسا",
  "GA": "الغابون",
  "GB": "المملكة المتحدة",
  "GD": "غرينادا",
  "GE": "جورجيا",
  "GF": "غويانا الفرنسية",
  "GG": "غيرنزي",
  "GH": "غانا",
  "GI": "جبل طارق",
  "GL": "غرينلاند",
  "GM": "غامبيا",
  "GN": "غينيا",
  "GP": "غوادلوب",
  "GQ": "غينيا الاستوائية",
  "GR": "اليونان",
  "GT": "غواتيمالا",
  "GU": "غوام",
  "GW": "غينيا بيساو",
  "GY": "غيانا",
  "HK": "هونغ كونغ الصينية (منطقة إدارية خاصة)",
  "HN": "هندوراس",
  "HR": "كرواتيا",
  "HT": "هايتي",
  "HU": "هنغاريا",
  "ID": "إندونيسيا",
  "IE": "أيرلندا",
  "IL": "إسرائيل",
  "IM": "جزيرة مان",
  "IN": "الهند",
  "IO": "الإقليم البريطاني في المحيط الهندي",
  "IQ": "العراق",
  "IR": "إيران",
  "IS": "آيسلندا",
  "IT": "إيطاليا",
  "JE": "جيرسي",
  "JM": "جامايكا",
  "JO": "الأردن",
  "JP": "اليابان",
  "KE": "كينيا",
  "KG": "قيرغيزستان",
  "KH": "كمبوديا",
  "KI": "كيريباتي",
  "KM": "جزر القمر",
  "KN": "سانت كيتس ونيفيس",
  "KP": "كوريا الشمالية",
  "KR": "كوريا الجنوبية",
  "KW": "الكويت",
  "KY": "جزر كايمان",
  "KZ": "كازاخستان",
  "LA": "لاوس",
  "LB": "لبنان",
  "LC": "سانت لوسيا",
  "LI": "ليختنشتاين",
  "LK": "سريلانكا",
  "LR": "ليبيريا",
  "LS": "ليسوتو",
  "LT": "ليتوانيا",
  "LU": "لوكسمبورغ",
  "LV": "لاتفيا",
  "LY": "ليبيا",
  "MA": "المغرب",
  "MC": "موناكو",
  "MD": "مولدوفا",
  "ME": "الجبل الأسود",
  "MF": "سان مارتن",
  "MG": "مدغشقر",
  "MH": "جزر مارشال",
  "MK": "مقدونيا الشمالية",
  "ML": "مالي",
  "MM": "ميانمار (بورما)",
  "MN": "منغوليا",
  "MO": "منطقة ماكاو الإدارية الخاصة",
  "MP": "جزر ماريانا الشمالية",
  "MQ": "جزر المارتينيك",
  "MR": "موريتانيا",
  "MS": "مونتسرات",
  "MT": "مالطا",
  "MU": "موريشيوس",
  "MV": "جزر المالديف",
  "MW": "ملاوي",
  "MX": "المكسيك",
  "MY": "ماليزيا",
  "MZ": "موزمبيق",
  "NA": "ناميبيا",
  "NC": "كاليدونيا الجديدة",
  "NE": "النيجر",
  "NF": "جزيرة نورفولك",
  "NG": "نيجيريا",
  "NI": "نيكاراغوا",
  "NL": "هولندا",
  "NO": "النرويج",
  "NP": "نيبال",
  "NR": "ناورو",
  "NU": "نيوي",
  "NZ": "نيوزيلندا",
  "OM": "عُمان",
  "PA": "بنما",
  "PE": "بيرو",
  "PF": "بولينيزيا الفرنسية",
  "PG": "بابوا غينيا الجديدة",
  "PH": "الفلبين",
  "PK": "باكستان",
  "PL": "بولندا",
  "PM": "سان بيير ومكويلون",
  "PR": "بورتوريكو",
  "PS": "الأراضي الفلسطينية",
  "PT": "البرتغال",
  "PW": "بالاو",
  "PY": "باراغواي",
  "QA": "قطر",
  "RE": "روينيون",
  "RO": "رومانيا",
  "RS": "صربيا",
  "RU": "روسيا",
  "RW": "رواندا",
  "SA": "المملكة العربية السعودية",
  "SB": "جزر سليمان",
  "SC": "سيشل",
  "SD": "السودان",
  "SE": "السويد",
  "SG": "سنغافورة",
  "SH": "سانت هيلينا",
  "SI": "سلوفينيا",
  "SJ": "سفالبارد وجان ماين",
  "SK": "سلوفاكيا",
  "SL": "سيراليون",
  "SM": "سان مارينو",
  "SN": "السنغال",
  "SO": "الصومال",
  "SR": "سورينام",
  "SS": "جنوب السودان",
  "ST": "ساو تومي وبرينسيبي",
  "SV": "السلفادور",
  "SX": "سانت مارتن",
  "SY": "سوريا",
  "SZ": "إسواتيني",
  "TA": "تريستان دا كونا",
  "TC": "جزر توركس وكايكوس",
  "TD": "تشاد",
  "TG": "توغو",
  "TH": "تايلاند",
  "TJ": "طاجيكستان",
  "TK": "توكيلاو",
  "TL": "تيمور - ليشتي",
  "TM": "تركمانستان",
  "TN": "تونس",
  "TO": "تونغا",
  "TR": "تركيا",
  "TT": "ترينيداد وتوباغو",
  "TV": "توفالو",
  "TW": "تايوان",
  "TZ": "تنزانيا",
  "UA": "أوكرانيا",
  "UG": "أوغندا",
  "US": "الولايات المتحدة",
  "UY": "أورغواي",
  "UZ": "أوزبكستان",
  "VA": "الفاتيكان",
  "VC": "سانت فنسنت وجزر غرينادين",
  "VE": "فنزويلا",
  "VG": "جزر فيرجن البريطانية",
  "VI": "جزر فيرجن الأمريكية",
  "VN": "فيتنام",
  "VU": "فانواتو",
  "WF": "جزر والس وفوتونا",
  "WS": "ساموا",
  "XK": "كوسوفو",
  "YE": "اليمن",
  "YT": "مايوت",
  "ZA": "جنوب أفريقيا",
  "ZM": "زامبيا",
  "ZW": "زيمبابوي"
 },
 "de": {
  "AC": "Ascension",
  "AD": "Andorra",
  "AE": "Vereinigte Arabische Emirate",
  "AF": "Afghanistan",
  "AG": "Antigua und Barbuda",
  "AI": "Anguilla",
  "AL": "Albanien",
  "AM": "Armenien",
  "AO": "Angola",
  "AR": "Argentinien",
  "AS": "Amerikanisch-Samoa",
  "AT": "Österreich",
  "AU": "Australien",
  "AW": "Aruba",
  "AX": "Ålandinseln",
  "AZ": "Aserbaidschan",
  "BA": "Bosnien und Herzegowina",
  "BB": "Barbados",
  "BD": "Bangladesch",
  "BE": "Belgien",
  "BF": "Burkina Faso",
  "BG": "Bulgarien",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "St. Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei Darussalam",
  "BO": "Bolivien",
  "BQ": "Karibische Niederlande",
  "BR": "Brasilien",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BW": "Botsuana",
  "BY": "Belarus",
  "BZ": "Belize",
  "CA": "Kanada",
  "CC": "Kokosinseln",
  "CD": "Kongo-Kinshasa",
  "CF": "Zentralafrikanische Republik",
  "CG": "Kongo-Brazzaville",
  "CH": "Schweiz",
  "CI": "Côte d’Ivoire",
  "CK": "Cookinseln",
  "CL": "Chile",
  "CM": "Kamerun",
  "CN": "China",
  "CO": "Kolumbien",
  "CR": "Costa Rica",
  "CU": "Kuba",
  "CV": "Cabo Verde",
  "CW": "Curaçao",
  "CX": "Weihnachtsinsel",
  "CY": "Zypern",
  "CZ": "Tschechien",
  "DE": "Deutschland",
  "DJ": "Dschibuti",
  "DK": "Dänemark",
  "DM": "Dominica",
  "DO": "Dominikanische Republik",
  "DZ": "Algerien",
  "EC": "Ecuador",
  "EE": "Estland",
  "EG": "Ägypten",
  "EH": "Westsahara",
  "ER": "Eritrea",
  "ES": "Spanien",
  "ET": "Äthiopien",
  "FI": "Finnland",
  "FJ": "Fidschi",
  "FK": "Falklandinseln",
  "FM": "Mikronesien",
  "FO": "Färöer",
  "FR": "Frankreich",
  "GA": "Gabun",
  "GB": "Vereinigtes Königreich",
  "GD": "Grenada",
  "GE": "Georgien",
  "GF": "Französisch-Guayana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Grönland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Äquatorialguinea",
  "GR": "Griechenland",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HK": "Sonderverwaltungsregion Hongkong",
  "HN": "Honduras",
  "HR": "Kroatien",
  "HT": "Haiti",
  "HU": "Ungarn",
  "ID": "Indonesien",
  "IE": "Irland",
  "IL": "Israel",
  "IM": "Isle of Man",
  "IN": "Indien",
  "IO": "Britisches Territorium im Indischen Ozean",
  "IQ": "Irak",
  "IR": "Iran",
  "IS": "Island",
  "IT": "Italien",
  "JE": "Jersey",
  "JM": "Jamaika",
  "JO": "Jordanien",
  "JP": "Japan",
  "KE": "Kenia",
  "KG": "Kirgisistan",
  "KH": "Kambodscha",
  "KI": "Kiribati",
  "KM": "Komoren",
  "KN": "St. Kitts und Nevis",
  "KP": "Nordkorea",
  "KR": "Südkorea",
  "KW": "Kuwait",
  "KY": "Kaimaninseln",
  "KZ": "Kasachstan",
  "LA": "Laos",
  "LB": "Libanon",
  "LC": "St. Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Litauen",
  "LU": "Luxemburg",
  "LV": "Lettland",
  "LY": "Libyen",
  "MA": "Marokko",
  "MC": "Monaco",
  "MD": "Republik Moldau",
  "ME": "Montenegro",
  "MF": "St. Martin",
  "MG": "Madagaskar",
  "MH": "Marshallinseln",
  "MK": "Nordmazedonien",
  "ML": "Mali",
  "MM": "Myanmar",
  "MN": "Mongolei",
  "MO": "Sonderverwaltungsregion Macau",
  "MP": "Nördliche Marianen",
  "MQ": "Martinique",
  "MR": "Mauretanien",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Malediven",
  "MW": "Malawi",
  "MX": "Mexiko",
  "MY": "Malaysia",
  "MZ": "Mosambik",
  "NA": "Namibia",
  "NC": "Neukaledonien",
  "NE": "Niger",
  "NF": "Norfolkinsel",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Niederlande",
  "NO": "Norwegen",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Neuseeland",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "Französisch-Polynesien",
  "PG": "Papua-Neuguinea",
  "PH": "Philippinen",
  "PK": "Pakistan",
  "PL": "Polen",
  "PM": "St. Pierre und Miquelon",
  "PR": "Puerto Rico",
  "PS": "Palästinensische Autonomiegebiete",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Katar",
  "RE": "Réunion",
  "RO": "Rumänien",
  "RS": "Serbien",
  "RU": "Russland",
  "RW": "Ruanda",
  "SA": "Saudi-Arabien",
  "SB": "Salomonen",
  "SC": "Seychellen",
  "SD": "Sudan",
  "SE": "Schweden",
  "SG": "Singapur",
  "SH": "St. Helena",
  "SI": "Slowenien",
  "SJ": "Spitzbergen und Jan Mayen",
  "SK": "Slowakei",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "Südsudan",
  "ST": "São Tomé und Príncipe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Syrien",
  "SZ": "Eswatini",
  "TA": "Tristan da Cunha",
  "TC": "Turks- und Caicosinseln",
  "TD": "Tschad",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tadschikistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistan",
  "TN": "Tunesien",
  "TO": "Tonga",
  "TR": "Türkei",
  "TT": "Trinidad und Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tansania",
  "UA": "Ukraine",
  "UG": "Uganda",
  "US": "Vereinigte Staaten",
  "UY": "Uruguay",
  "UZ": "Usbekistan",
  "VA": "Vatikanstadt",
  "VC": "St. Vincent und die Grenadinen",
  "VE": "Venezuela",
  "VG": "Britische Jungferninseln",
  "VI": "Amerikanische Jungferninseln",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "WF": "Wallis und Futuna",
  "WS": "Samoa",
  "XK": "Kosovo",
  "YE": "Jemen",
  "YT": "Mayotte",
  "ZA": "Südafrika",
  "ZM": "Sambia",
  "ZW": "Simbabwe"
 },
 "es": {
  "AC": "Isla de la Ascensión",
  "AD": "Andorra",
  "AE": "Emiratos Árabes Unidos",
  "AF": "Afganistán",
  "AG": "Antigua y Barbuda",
  "AI": "Anguila",
  "AL": "Albania",
  "AM": "Armenia",
  "AO": "Angola",
  "AR": "Argentina",
  "AS": "Samoa Americana",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "Islas Aland",
  "AZ": "Azerbaiyán",
  "BA": "Bosnia y Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladés",
  "BE": "Bélgica",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Baréin",
  "BI": "Burundi",
  "BJ": "Benín",
  "BL": "San Bartolomé",
  "BM": "Bermudas",
  "BN": "Brunéi",
  "BO": "Bolivia",
  "BQ": "Caribe neerlandés",
  "BR": "Brasil",
  "BS": "Bahamas",
  "BT": "Bután",
  "BW": "Botsuana",
  "BY": "Bielorrusia",
  "BZ": "Belice",
  "CA": "Canadá",
  "CC": "Islas Cocos",
  "CD": "República Democrática del Congo",
  "CF": "República Centroafricana",
  "CG": "Congo",
  "CH": "Suiza",
  "CI": "Côte d’Ivoire",
  "CK": "Islas Cook",
  "CL": "Chile",
  "CM": "Camerún",
  "CN": "China",
  "CO": "Colombia",
  "CR": "Costa Rica",
  "CU": "Cuba",
  "CV": "Cabo Verde",
  "CW": "Curazao",
  "CX": "Isla de Navidad",
  "CY": "Chipre",
  "CZ": "Chequia",
  "DE": "Alemania",
  "DJ": "Yibuti",
  "DK": "Dinamarca",
  "DM": "Dominica",
  "DO": "República Dominicana",
  "DZ": "Argelia",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egipto",
  "EH": "Sáhara Occidental",
  "ER": "Eritrea",
  "ES": "España",
  "ET": "Etiopía",
  "FI": "Finlandia",
  "FJ": "Fiyi",
  "FK": "Islas Malvinas",
  "FM": "Micronesia",
  "FO": "Islas Feroe",
  "FR": "Francia",
  "GA": "Gabón",
  "GB": "Reino Unido",
  "GD": "Granada",
  "GE": "Georgia",
  "GF": "Guayana Francesa",
  "GG": "Guernesey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Groenlandia",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadalupe",
  "GQ": "Guinea Ecuatorial",
  "GR": "Grecia",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bisáu",
  "GY": "Guyana",
  "HK": "RAE de Hong Kong (China)",
  "HN": "Honduras",
  "HR": "Croacia",
  "HT": "Haití",
  "HU": "Hungría",
  "ID": "Indonesia",
  "IE": "Irlanda",
  "IL": "Israel",
  "IM": "Isla de Man",
  "IN": "India",
  "IO": "Territorio Británico del Océano Índico",
  "IQ": "Irak",
  "IR": "Irán",
  "IS": "Islandia",
  "IT": "Italia",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordania",
  "JP": "Japón",
  "KE": "Kenia",
  "KG": "Kirguistán",
  "KH": "Camboya",
  "KI": "Kiribati",
  "KM": "Comoras",
  "KN": "San Cristóbal y Nieves",
  "KP": "Corea del Norte",
  "KR": "Corea del Sur",
  "KW": "Kuwait",
  "KY": "Islas Caimán",
  "KZ": "Kazajistán",
  "LA": "Laos",
  "LB": "Líbano",
  "LC": "Santa Lucía",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesoto",
  "LT": "Lituania",
  "LU": "Luxemburgo",
  "LV": "Letonia",
  "LY": "Libia",
  "MA": "Marruecos",
  "MC": "Mónaco",
  "MD": "Moldavia",
  "ME": "Montenegro",
  "MF": "San Martín",
  "MG": "Madagascar",
  "MH": "Islas Marshall",
  "MK": "Macedonia del Norte",
  "ML": "Mali",
  "MM": "Myanmar (Birmania)",
  "MN": "Mongolia",
  "MO": "RAE de Macao (China)",
  "MP": "Islas Marianas del Norte",
  "MQ": "Martinica",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauricio",
  "MV": "Maldivas",
  "MW": "Malaui",
  "MX": "México",
  "MY": "Malasia",
  "MZ": "Mozambique",
  "NA": "Namibia",
  "NC": "Nueva Caledonia",
  "NE": "Níger",
  "NF": "Isla Norfolk",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Países Bajos",
  "NO": "Noruega",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Nueva Zelanda",
  "OM": "Omán",
  "PA": "Panamá",
  "PE": "Perú",
  "PF": "Polinesia Francesa",
  "PG": "Papúa Nueva Guinea",
  "PH": "Filipinas",
  "PK": "Pakistán",
  "PL": "Polonia",
  "PM": "San Pedro y Miquelón",
  "PR": "Puerto Rico",
  "PS": "Territorios Palestinos",
  "PT": "Portugal",
  "PW": "Palaos",
  "PY": "Paraguay",
  "QA": "Catar",
  "RE": "Reunión",
  "RO": "Rumanía",
  "RS": "Serbia",
  "RU": "Rusia",
  "RW": "Ruanda",
  "SA": "Arabia Saudí",
  "SB": "Islas Salomón",
  "SC": "Seychelles",
  "SD": "Sudán",
  "SE": "Suecia",
  "SG": "Singapur",
  "SH": "Santa Elena",
  "SI": "Eslovenia",
  "SJ": "Svalbard y Jan Mayen",
  "SK": "Eslovaquia",
  "SL": "Sierra Leona",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Surinam",
  "SS": "Sudán del Sur",
  "ST": "Santo Tomé y Príncipe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Siria",
  "SZ": "Esuatini",
  "TA": "Tristán de Acuña",
  "TC": "Islas Turcas y Caicos",
  "TD": "Chad",
  "TG": "Togo",
  "TH": "Tailandia",
  "TJ": "Tayikistán",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistán",
  "TN": "Túnez",
  "TO": "Tonga",
  "TR": "Turquía",
  "TT": "Trinidad y Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwán",
  "TZ": "Tanzania",
  "UA": "Ucrania",
  "UG": "Uganda",
  "US": "Estados Unidos",
  "UY": "Uruguay",
  "UZ": "Uzbekistán",
  "VA": "Ciudad del Vaticano",
  "VC": "San Vicente y las Granadinas",
  "VE": "Venezuela",
  "VG": "Islas Vírgenes Británicas",
  "VI": "Islas Vírgenes de EE. UU.",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "WF": "Wallis y Futuna",
  "WS": "Samoa",
  "XK": "Kosovo",
  "YE": "Yemen",
  "YT": "Mayotte",
  "ZA": "Sudáfrica",
  "ZM": "Zambia",
  "ZW": "Zimbabue"
 },
 "fr": {
  "AC": "Île de l’Ascension",
  "AD": "Andorre",
  "AE": "Émirats arabes unis",
  "AF": "Afghanistan",
  "AG": "Antigua-et-Barbuda",
  "AI": "Anguilla",
  "AL": "Albanie",
  "AM": "Arménie",
  "AO": "Angola",
  "AR": "Argentine",
  "AS": "Samoa américaines",
  "AT": "Autriche",
  "AU": "Australie",
  "AW": "Aruba",
  "AX": "Îles Åland",
  "AZ": "Azerbaïdjan",
  "BA": "Bosnie-Herzégovine",
  "BB": "Barbade",
  "BD": "Bangladesh",
  "BE": "Belgique",
  "BF": "Burkina Faso",
  "BG": "Bulgarie",
  "BH": "Bahreïn",
  "BI": "Burundi",
  "BJ": "Bénin",
  "BL": "Saint-Barthélemy",
  "BM": "Bermudes",
  "BN": "Brunei",
  "BO": "Bolivie",
  "BQ": "Pays-Bas caribéens",
  "BR": "Brésil",
  "BS": "Bahamas",
  "BT": "Bhoutan",
  "BW": "Botswana",
  "BY": "Biélorussie",
  "BZ": "Belize",
  "CA": "Canada",
  "CC": "Îles Cocos",
  "CD": "Congo-Kinshasa",
  "CF": "République centrafricaine",
  "CG": "Congo-Brazzaville",
  "CH": "Suisse",
  "CI": "Côte d’Ivoire",
  "CK": "Îles Cook",
  "CL": "Chili",
  "CM": "Cameroun",
  "CN": "Chine",
  "CO": "Colombie",
  "CR": "Costa Rica",
  "CU": "Cuba",
  "CV": "Cap-Vert",
  "CW": "Curaçao",
  "CX": "Île Christmas",
  "CY": "Chypre",
  "CZ": "Tchéquie",
  "DE": "Allemagne",
  "DJ": "Djibouti",
  "DK": "Danemark",
  "DM": "Dominique",
  "DO": "République dominicaine",
  "DZ": "Algérie",
  "EC": "Équateur",
  "EE": "Estonie",
  "EG": "Égypte",
  "EH": "Sahara occidental",
  "ER": "Érythrée",
  "ES": "Espagne",
  "ET": "Éthiopie",
  "FI": "Finlande",
  "FJ": "Fidji",
  "FK": "Îles Malouines",
  "FM": "Micronésie",
  "FO": "Îles Féroé",
  "FR": "France",
  "GA": "Gabon",
  "GB": "Royaume-Uni",
  "GD": "Grenade",
  "GE": "Géorgie",
  "GF": "Guyane française",
  "GG": "Guernesey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Groenland",
  "GM": "Gambie",
  "GN": "Guinée",
  "GP": "Guadeloupe",
  "GQ": "Guinée équatoriale",
  "GR": "Grèce",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinée-Bissau",
  "GY": "Guyana",
  "HK": "R.A.S. chinoise de Hong Kong",
  "HN": "Honduras",
  "HR": "Croatie",
  "HT": "Haïti",
  "HU": "Hongrie",
  "ID": "Indonésie",
  "IE": "Irlande",
  "IL": "Israël",
  "IM": "Île de Man",
  "IN": "Inde",
  "IO": "Territoire britannique de l’océan Indien",
  "IQ": "Irak",
  "IR": "Iran",
  "IS": "Islande",
  "IT": "Italie",
  "JE": "Jersey",
  "JM": "Jamaïque",
  "JO": "Jordanie",
  "JP": "Japon",
  "KE": "Kenya",
  "KG": "Kirghizstan",
  "KH": "Cambodge",
  "KI": "Kiribati",
  "KM": "Comores",
  "KN": "Saint-Christophe-et-Niévès",
  "KP": "Corée du Nord",
  "KR": "Corée du Sud",
  "KW": "Koweït",
  "KY": "Îles Caïmans",
  "KZ": "Kazakhstan",
  "LA": "Laos",
  "LB": "Liban",
  "LC": "Sainte-Lucie",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lituanie",
  "LU": "Luxembourg",
  "LV": "Lettonie",
  "LY": "Libye",
  "MA": "Maroc",
  "MC": "Monaco",
  "MD": "Moldavie",
  "ME": "Monténégro",
  "MF": "Saint-Martin",
  "MG": "Madagascar",
  "MH": "Îles Marshall",
  "MK": "Macédoine du Nord",
  "ML": "Mali",
  "MM": "Myanmar (Birmanie)",
  "MN": "Mongolie",
  "MO": "R.A.S. chinoise de Macao",
  "MP": "Îles Mariannes du Nord",
  "MQ": "Martinique",
  "MR": "Mauritanie",
  "MS": "Montserrat",
  "MT": "Malte",
  "MU": "Maurice",
  "MV": "Maldives",
  "MW": "Malawi",
  "MX": "Mexique",
  "MY": "Malaisie",
  "MZ": "Mozambique",
  "NA": "Namibie",
  "NC": "Nouvelle-Calédonie",
  "NE": "Niger",
  "NF": "Île Norfolk",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Pays-Bas",
  "NO": "Norvège",
  "NP": "Népal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Nouvelle-Zélande",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Pérou",
  "PF": "Polynésie française",
  "PG": "Papouasie-Nouvelle-Guinée",
  "PH": "Philippines",
  "PK": "Pakistan",
  "PL": "Pologne",
  "PM": "Saint-Pierre-et-Miquelon",
  "PR": "Porto Rico",
  "PS": "Territoires palestiniens",
  "PT": "Portugal",
  "PW": "Palaos",
  "PY": "Paraguay",
  "QA": "Qatar",
  "RE": "La Réunion",
  "RO": "Roumanie",
  "RS": "Serbie",
  "RU": "Russie",
  "RW": "Rwanda",
  "SA": "Arabie saoudite",
  "SB": "Îles Salomon",
  "SC": "Seychelles",
  "SD": "Soudan",
  "SE": "Suède",
  "SG": "Singapour",
  "SH": "Sainte-Hélène",
  "SI": "Slovénie",
  "SJ": "Svalbard et Jan Mayen",
  "SK": "Slovaquie",
  "SL": "Sierra Leone",
  "SM": "Saint-Marin",
  "SN": "Sénégal",
  "SO": "Somalie",
  "SR": "Suriname",
  "SS": "Soudan du Sud",
  "ST": "Sao Tomé-et-Principe",
  "SV": "Salvador",
  "SX": "Saint-Martin (partie néerlandaise)",
  "SY": "Syrie",
  "SZ": "Eswatini",
  "TA": "Tristan da Cunha",
  "TC": "Îles Turques-et-Caïques",
  "TD": "Tchad",
  "TG": "Togo",
  "TH": "Thaïlande",
  "TJ": "Tadjikistan",
  "TK": "Tokelau",
  "TL": "Timor oriental",
  "TM": "Turkménistan",
  "TN": "Tunisie",
  "TO": "Tonga",
  "TR": "Turquie",
  "TT": "Trinité-et-Tobago",
  "TV": "Tuvalu",
  "TW": "Taïwan",
  "TZ": "Tanzanie",
  "UA": "Ukraine",
  "UG": "Ouganda",
  "US": "États-Unis",
  "UY": "Uruguay",
  "UZ": "Ouzbékistan",
  "VA": "État de la Cité du Vatican",
  "VC": "Saint-Vincent-et-les Grenadines",
  "VE": "Venezuela",
  "VG": "Îles Vierges britanniques",
  "VI": "Îles Vierges des États-Unis",
  "VN": "Viêt Nam",
  "VU": "Vanuatu",
  "WF": "Wallis-et-Futuna",
  "WS": "Samoa",
  "XK": "Kosovo",
  "YE": "Yémen",
  "YT": "Mayotte",
  "ZA": "Afrique du Sud",
  "ZM": "Zambie",
  "ZW": "Zimbabwe"
 },
 "hi": {
  "AC": "असेंशन द्वीप",
  "AD": "एंडोरा",
  "AE": "संयुक्त अरब अमीरात",
  "AF": "अफ़गानिस्तान",
  "AG": "एंटिगुआ और बरबुडा",
  "AI": "एंग्विला",
  "AL": "अल्बानिया",
  "AM": "आर्मेनिया",
  "AO": "अंगोला",
  "AR": "अर्जेंटीना",
  "AS": "अमेरिकी समोआ",
  "AT": "ऑस्ट्रिया",
  "AU": "ऑस्ट्रेलिया",
  "AW": "अरूबा",
  "AX": "एलैंड द्वीपसमूह",
  "AZ": "अज़रबैजान",
  "BA": "बोस्निया और हर्ज़ेगोविना",
  "BB": "बारबाडोस",
  "BD": "बांग्लादेश",
  "BE": "बेल्जियम",
  "BF": "बुर्किना फ़ासो",
  "BG": "बुल्गारिया",
  "BH": "बहरीन",
  "BI": "बुरुंडी",
  "BJ": "बेनिन",
  "BL": "सेंट बार्थेलेमी",
  "BM": "बरमूडा",
  "BN": "ब्रूनेई",
  "BO": "बोलीविया",
  "BQ": "कैरिबियन नीदरलैंड",
  "BR": "ब्राज़ील",
  "BS": "बहामास",
  "BT": "भूटान",
  "BW": "बोत्स्वाना",
  "BY": "बेलारूस",
  "BZ": "बेलीज़",
  "CA": "कनाडा",
  "CC": "कोकोस (कीलिंग) द्वीपसमूह",
  "CD": "कांगो - किंशासा",
  "CF": "मध्य अफ़्रीकी गणराज्य",
  "CG": "कांगो – ब्राज़ाविल",
  "CH": "स्विट्ज़रलैंड",
  "CI": "कोत दिवुआर",
  "CK": "कुक द्वीपसमूह",
  "CL": "चिली",
  "CM": "कैमरून",
  "CN": "चीन",
  "CO": "कोलंबिया",
  "CR": "कोस्टारिका",
  "CU": "क्यूबा",
  "CV": "केप वर्ड",
  "CW": "कुरासाओ",
  "CX": "क्रिसमस द्वीप",
  "CY": "साइप्रस",
  "CZ": "चेकिया",
  "DE": "जर्मनी",
  "DJ": "जिबूती",
  "DK": "डेनमार्क",
  "DM": "डोमिनिका",
  "DO": "डोमिनिकन गणराज्य",
  "DZ": "अल्जीरिया",
  "EC": "इक्वाडोर",
  "EE": "एस्टोनिया",
  "EG": "मिस्र",
  "EH": "पश्चिमी सहारा",
  "ER": "इरिट्रिया",
  "ES": "स्पेन",
  "ET": "इथियोपिया",
  "FI": "फ़िनलैंड",
  "FJ": "फ़िजी",
  "FK": "फ़ॉकलैंड द्वीपसमूह",
  "FM": "माइक्रोनेशिया",
  "FO": "फ़ेरो द्वीपसमूह",
  "FR": "फ़्रांस",
  "GA": "गैबॉन",
  "GB": "यूनाइटेड किंगडम",
  "GD": "ग्रेनाडा",
  "GE": "जॉर्जिया",
  "GF": "फ़्रेंच गुयाना",
  "GG": "गर्नसी",
  "GH": "घाना",
  "GI": "जिब्राल्टर",
  "GL": "ग्रीनलैंड",
  "GM": "गाम्बिया",
  "GN": "गिनी",
  "GP": "ग्वाडेलूप",
  "GQ": "इक्वेटोरियल गिनी",
  "GR": "यूनान",
  "GT": "ग्वाटेमाला",
  "GU": "गुआम",
  "GW": "गिनी-बिसाउ",
  "GY": "गुयाना",
  "HK": "हाँग काँग (चीन विशेष प्रशासनिक क्षेत्र)",
  "HN": "होंडूरास",
  "HR": "क्रोएशिया",
  "HT": "हैती",
  "HU": "हंगरी",
  "ID": "इंडोनेशिया",
  "IE": "आयरलैंड",
  "IL": "इज़राइल",
  "IM": "आइल ऑफ़ मैन",
  "IN": "भारत",
  "IO": "ब्रिटिश हिंद महासागरीय क्षेत्र",
  "IQ": "इराक",
  "IR": "ईरान",
  "IS": "आइसलैंड",
  "IT": "इटली",
  "JE": "जर्सी",
  "JM": "जमैका",
  "JO": "जॉर्डन",
  "JP": "जापान",
  "KE": "केन्या",
  "KG": "किर्गिज़स्तान",
  "KH": "कंबोडिया",
  "KI": "किरिबाती",
  "KM": "कोमोरोस",
  "KN": "सेंट किट्स और नेविस",
  "KP": "उत्तर कोरिया",
  "KR": "दक्षिण कोरिया",
  "KW": "कुवैत",
  "KY": "कैमेन द्वीपसमूह",
  "KZ": "कज़ाखस्तान",
  "LA": "लाओस",
  "LB": "लेबनान",
  "LC": "सेंट लूसिया",
  "LI": "लिचेंस्टीन",
  "LK": "श्रीलंका",
  "LR": "लाइबेरिया",
  "LS": "लेसोथो",
  "LT": "लिथुआनिया",
  "LU": "लग्ज़मबर्ग",
  "LV": "लातविया",
  "LY": "लीबिया",
  "MA": "मोरक्को",
  "MC": "मोनाको",
  "MD": "मॉल्डोवा",
  "ME": "मोंटेनेग्रो",
  "MF": "सेंट मार्टिन",
  "MG": "मेडागास्कर",
  "MH": "मार्शल द्वीपसमूह",
  "MK": "उत्तरी मकदूनिया",
  "ML": "माली",
  "MM": "म्यांमार (बर्मा)",
  "MN": "मंगोलिया",
  "MO": "मकाऊ (विशेष प्रशासनिक क्षेत्र चीन)",
  "MP": "उत्तरी मारियाना द्वीपसमूह",
  "MQ": "मार्टीनिक",
  "MR": "मॉरिटानिया",
  "MS": "मोंटसेरात",
  "MT": "माल्टा",
  "MU": "मॉरीशस",
  "MV": "मालदीव",
  "MW": "मलावी",
  "MX": "मैक्सिको",
  "MY": "मलेशिया",
  "MZ": "मोज़ांबिक",
  "NA": "नामीबिया",
  "NC": "न्यू कैलेडोनिया",
  "NE": "नाइजर",
  "NF": "नॉरफ़ॉक द्वीप",
  "NG": "नाइजीरिया",
  "NI": "निकारागुआ",
  "NL": "नीदरलैंड",
  "NO": "नॉर्वे",
  "NP": "नेपाल",
  "NR": "नाउरु",
  "NU": "नीयू",
  "NZ": "न्यूज़ीलैंड",
  "OM": "ओमान",
  "PA": "पनामा",
  "PE": "पेरू",
  "PF": "फ़्रेंच पोलिनेशिया",
  "PG": "पापुआ न्यू गिनी",
  "PH": "फ़िलिपींस",
  "PK": "पाकिस्तान",
  "PL": "पोलैंड",
  "PM": "सेंट पिएरे और मिक्वेलान",
  "PR": "पोर्टो रिको",
  "PS": "फ़िलिस्तीनी क्षेत्र",
  "PT": "पुर्तगाल",
  "PW": "पलाऊ",
  "PY": "पराग्वे",
  "QA": "क़तर",
  "RE": "रियूनियन",
  "RO": "रोमानिया",
  "RS": "सर्बिया",
  "RU": "रूस",
  "RW": "रवांडा",
  "SA": "सऊदी अरब",
  "SB": "सोलोमन द्वीपसमूह",
  "SC": "सेशेल्स",
  "SD": "सूडान",
  "SE": "स्वीडन",
  "SG": "सिंगापुर",
  "SH": "सेंट हेलेना",
  "SI": "स्लोवेनिया",
  "SJ": "स्वालबार्ड और जान मायेन",
  "SK": "स्लोवाकिया",
  "SL": "सिएरा लियोन",
  "SM": "सैन मेरीनो",
  "SN": "सेनेगल",
  "SO": "सोमालिया",
  "SR": "सूरीनाम",
  "SS": "दक्षिण सूडान",
  "ST": "साओ टोम और प्रिंसिपे",
  "SV": "अल सल्वाडोर",
  "SX": "सिंट मार्टिन",
  "SY": "सीरिया",
  "SZ": "एस्वाटिनी",
  "TA": "ट्रिस्टन दा कुना",
  "TC": "तुर्क और कैकोज़ द्वीपसमूह",
  "TD": "चाड",
  "TG": "टोगो",
  "TH": "थाईलैंड",
  "TJ": "ताजिकिस्तान",
  "TK": "तोकेलाउ",
  "TL": "तिमोर-लेस्त",
  "TM": "तुर्कमेनिस्तान",
  "TN": "ट्यूनीशिया",
  "TO": "टोंगा",
  "TR": "तुर्किये",
  "TT": "त्रिनिदाद और टोबैगो",
  "TV": "तुवालू",
  "TW": "ताइवान",
  "TZ": "तंज़ानिया",
  "UA": "यूक्रेन",
  "UG": "युगांडा",
  "US": "संयुक्त राज्य",
  "UY": "उरूग्वे",
  "UZ": "उज़्बेकिस्तान",
  "VA": "वेटिकन सिटी",
  "VC": "सेंट विंसेंट और ग्रेनाडाइंस",
  "VE": "वेनेज़ुएला",
  "VG": "ब्रिटिश वर्जिन द्वीपसमूह",
  "VI": "यू॰एस॰ वर्जिन द्वीपसमूह",
  "VN": "वियतनाम",
  "VU": "वनुआतू",
  "WF": "वालिस और फ़्यूचूना",
  "WS": "समोआ",
  "XK": "कोसोवो",
  "YE": "यमन",
  "YT": "मायोते",
  "ZA": "दक्षिण अफ़्रीका",
  "ZM": "ज़ाम्बिया",
  "ZW": "ज़िम्बाब्वे"
 },
 "ja": {
  "AC": "アセンション島",
  "AD": "アンドラ",
  "AE": "アラブ首長国連邦",
  "AF": "アフガニスタン",
  "AG": "アンティグア・バーブーダ",
  "AI": "アンギラ",
  "AL": "アルバニア",
  "AM": "アルメニア",
  "AO": "アンゴラ",
  "AR": "アルゼンチン",
  "AS": "米領サモア",
  "AT": "オーストリア",
  "AU": "オーストラリア",
  "AW": "アルバ",
  "AX": "オーランド諸島",
  "AZ": "アゼルバイジャン",
  "BA": "ボスニア・ヘルツェゴビナ",
  "BB": "バルバドス",
  "BD": "バングラデシュ",
  "BE": "ベルギー",
  "BF": "ブルキナファソ",
  "BG": "ブルガリア",
  "BH": "バーレーン",
  "BI": "ブルンジ",
  "BJ": "ベナン",
  "BL": "サン・バルテルミー",
  "BM": "バミューダ",
  "BN": "ブルネイ",
  "BO": "ボリビア",
  "BQ": "オランダ領カリブ",
  "BR": "ブラジル",
  "BS": "バハマ",
  "BT": "ブータン",
  "BW": "ボツワナ",
  "BY": "ベラルーシ",
  "BZ": "ベリーズ",
  "CA": "カナダ",
  "CC": "ココス(キーリング)諸島",
  "CD": "コンゴ民主共和国(キンシャサ)",
  "CF": "中央アフリカ共和国",
  "CG": "コンゴ共和国(ブラザビル)",
  "CH": "スイス",
  "CI": "コートジボワール",
  "CK": "クック諸島",
  "CL": "チリ",
  "CM": "カメルーン",
  "CN": "中国",
  "CO": "コロンビア",
  "CR": "コスタリカ",
  "CU": "キューバ",
  "CV": "カーボベルデ",
  "CW": "キュラソー",
  "CX": "クリスマス島",
  "CY": "キプロス",
  "CZ": "チェコ",
  "DE": "ドイツ",
  "DJ": "ジブチ",
  "DK": "デンマーク",
  "DM": "ドミニカ国",
  "DO": "ドミニカ共和国",
  "DZ": "アルジェリア",
  "EC": "エクアドル",
  "EE": "エストニア",
  "EG": "エジプト",
  "EH": "西サハラ",
  "ER": "エリトリア",
  "ES": "スペイン",
  "ET": "エチオピア",
  "FI": "フィンランド",
  "FJ": "フィジー",
  "FK": "フォークランド諸島",
  "FM": "ミクロネシア連邦",
  "FO": "フェロー諸島",
  "FR": "フランス",
  "GA": "ガボン",
  "GB": "イギリス",
  "GD": "グレナダ",
  "GE": "ジョージア",
  "GF": "仏領ギアナ",
  "GG": "ガーンジー",
  "GH": "ガーナ",
  "GI": "ジブラルタル",
  "GL": "グリーンランド",
  "GM": "ガンビア",
  "GN": "ギニア",
  "GP": "グアドループ",
  "GQ": "赤道ギニア",
  "GR": "ギリシャ",
  "GT": "グアテマラ",
  "GU": "グアム",
  "GW": "ギニアビサウ",
  "GY": "ガイアナ",
  "HK": "中華人民共和国香港特別行政区",
  "HN": "ホンジュラス",
  "HR": "クロアチア",
  "HT": "ハイチ",
  "HU": "ハンガリー",
  "ID": "インドネシア",
  "IE": "アイルランド",
  "IL": "イスラエル",
  "IM": "マン島",
  "IN": "インド",
  "IO": "英領インド洋地域",
  "IQ": "イラク",
  "IR": "イラン",
  "IS": "アイスランド",
  "IT": "イタリア",
  "JE": "ジャージー",
  "JM": "ジャマイカ",
  "JO": "ヨルダン",
  "JP": "日本",
  "KE": "ケニア",
  "KG": "キルギス",
  "KH": "カンボジア",
  "KI": "キリバス",
  "KM": "コモロ",
  "KN": "セントクリストファー・ネーヴィス",
  "KP": "北朝鮮",
  "KR": "韓国",
  "KW": "クウェート",
  "KY": "ケイマン諸島",
  "KZ": "カザフスタン",
  "LA": "ラオス",
  "LB": "レバノン",
  "LC": "セントルシア",
  "LI": "リヒテンシュタイン",
  "LK": "スリランカ",
  "LR": "リベリア",
  "LS": "レソト",
  "LT": "リトアニア",
  "LU": "ルクセンブルク",
  "LV": "ラトビア",
  "LY": "リビア",
  "MA": "モロッコ",
  "MC": "モナコ",
  "MD": "モルドバ",
  "ME": "モンテネグロ",
  "MF": "サン・マルタン",
  "MG": "マダガスカル",
  "MH": "マーシャル諸島",
  "MK": "北マケドニア",
  "ML": "マリ",
  "MM": "ミャンマー (ビルマ)",
  "MN": "モンゴル",
  "MO": "中華人民共和国マカオ特別行政区",
  "MP": "北マリアナ諸島",
  "MQ": "マルティニーク",
  "MR": "モーリタニア",
  "MS": "モントセラト",
  "MT": "マルタ",
  "MU": "モーリシャス",
  "MV": "モルディブ",
  "MW": "マラウイ",
  "MX": "メキシコ",
  "MY": "マレーシア",
  "MZ": "モザンビーク",
  "NA": "ナミビア",
  "NC": "ニューカレドニア",
  "NE": "ニジェール",
  "NF": "ノーフォーク島",
  "NG": "ナイジェリア",
  "NI": "ニカラグア",
  "NL": "オランダ",
  "NO": "ノルウェー",
  "NP": "ネパール",
  "NR": "ナウル",
  "NU": "ニウエ",
  "NZ": "ニュージーランド",
  "OM": "オマーン",
  "PA": "パナマ",
  "PE": "ペルー",
  "PF": "仏領ポリネシア",
  "PG": "パプアニューギニア",
  "PH": "フィリピン",
  "PK": "パキスタン",
  "PL": "ポーランド",
  "PM": "サンピエール島・ミクロン島",
  "PR": "プエルトリコ",
  "PS": "パレスチナ自治区",
  "PT": "ポルトガル",
  "PW": "パラオ",
  "PY": "パラグアイ",
  "QA": "カタール",
  "RE": "レユニオン",
  "RO": "ルーマニア",
  "RS": "セルビア",
  "RU": "ロシア",
  "RW": "ルワンダ",
  "SA": "サウジアラビア",
  "SB": "ソロモン諸島",
  "SC": "セーシェル",
  "SD": "スーダン",
  "SE": "スウェーデン",
  "SG": "シンガポール",
  "SH": "セントヘレナ",
  "SI": "スロベニア",
  "SJ": "スバールバル諸島・ヤンマイエン島",
  "SK": "スロバキア",
  "SL": "シエラレオネ",
  "SM": "サンマリノ",
  "SN": "セネガル",
  "SO": "ソマリア",
  "SR": "スリナム",
  "SS": "南スーダン",
  "ST": "サントメ・プリンシペ",
  "SV": "エルサルバドル",
  "SX": "シント・マールテン",
  "SY": "シリア",
  "SZ": "エスワティニ",
  "TA": "トリスタン・ダ・クーニャ",
  "TC": "タークス・カイコス諸島",
  "TD": "チャド",
  "TG": "トーゴ",
  "TH": "タイ",
  "TJ": "タジキスタン",
  "TK": "トケラウ",
  "TL": "東ティモール",
  "TM": "トルクメニスタン",
  "TN": "チュニジア",
  "TO": "トンガ",
  "TR": "トルコ",
  "TT": "トリニダード・トバゴ",
  "TV": "ツバル",
  "TW": "台湾",
  "TZ": "タンザニア",
  "UA": "ウクライナ",
  "UG": "ウガンダ",
  "US": "アメリカ合衆国",
  "UY": "ウルグアイ",
  "UZ": "ウズベキスタン",
  "VA": "バチカン市国",
  "VC": "セントビンセント及びグレナディーン諸島",
  "VE": "ベネズエラ",
  "VG": "英領ヴァージン諸島",
  "VI": "米領ヴァージン諸島",
  "VN": "ベトナム",
  "VU": "バヌアツ",
  "WF": "ウォリス・フツナ",
  "WS": "サモア",
  "XK": "コソボ",
  "YE": "イエメン",
  "YT": "マヨット",
  "ZA": "南アフリカ",
  "ZM": "ザンビア",
  "ZW": "ジンバブエ"
 },
 "pt": {
  "AC": "Ilha de Ascensão",
  "AD": "Andorra",
  "AE": "Emirados Árabes Unidos",
  "AF": "Afeganistão",
  "AG": "Antígua e Barbuda",
  "AI": "Anguila",
  "AL": "Albânia",
  "AM": "Armênia",
  "AO": "Angola",
  "AR": "Argentina",
  "AS": "Samoa Americana",
  "AT": "Áustria",
  "AU": "Austrália",
  "AW": "Aruba",
  "AX": "Ilhas Aland",
  "AZ": "Azerbaijão",
  "BA": "Bósnia e Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Bélgica",
  "BF": "Burquina Faso",
  "BG": "Bulgária",
  "BH": "Barein",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "São Bartolomeu",
  "BM": "Bermudas",
  "BN": "Brunei",
  "BO": "Bolívia",
  "BQ": "Países Baixos Caribenhos",
  "BR": "Brasil",
  "BS": "Bahamas",
  "BT": "Butão",
  "BW": "Botsuana",
  "BY": "Bielorrússia",
  "BZ": "Belize",
  "CA": "Canadá",
  "CC": "Ilhas Cocos (Keeling)",
  "CD": "Congo - Kinshasa",
  "CF": "República Centro-Africana",
  "CG": "República do Congo",
  "CH": "Suíça",
  "CI": "Costa do Marfim",
  "CK": "Ilhas Cook",
  "CL": "Chile",
  "CM": "Camarões",
  "CN": "China",
  "CO": "Colômbia",
  "CR": "Costa Rica",
  "CU": "Cuba",
  "CV": "Cabo Verde",
  "CW": "Curaçao",
  "CX": "Ilha Christmas",
  "CY": "Chipre",
  "CZ": "Tchéquia",
  "DE": "Alemanha",
  "DJ": "Djibuti",
  "DK": "Dinamarca",
  "DM": "Dominica",
  "DO": "República Dominicana",
  "DZ": "Argélia",
  "EC": "Equador",
  "EE": "Estônia",
  "EG": "Egito",
  "EH": "Saara Ocidental",
  "ER": "Eritreia",
  "ES": "Espanha",
  "ET": "Etiópia",
  "FI": "Finlândia",
  "FJ": "Fiji",
  "FK": "Ilhas Malvinas",
  "FM": "Micronésia",
  "FO": "Ilhas Faroé",
  "FR": "França",
  "GA": "Gabão",
  "GB": "Reino Unido",
  "GD": "Granada",
  "GE": "Geórgia",
  "GF": "Guiana Francesa",
  "GG": "Guernsey",
  "GH": "Gana",
  "GI": "Gibraltar",
  "GL": "Groenlândia",
  "GM": "Gâmbia",
  "GN": "Guiné",
  "GP": "Guadalupe",
  "GQ": "Guiné Equatorial",
  "GR": "Grécia",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guiné-Bissau",
  "GY": "Guiana",
  "HK": "Hong Kong, RAE da China",
  "HN": "Honduras",
  "HR": "Croácia",
  "HT": "Haiti",
  "HU": "Hungria",
  "ID": "Indonésia",
  "IE": "Irlanda",
  "IL": "Israel",
  "IM": "Ilha de Man",
  "IN": "Índia",
  "IO": "Território Britânico do Oceano Índico",
  "IQ": "Iraque",
  "IR": "Irã",
  "IS": "Islândia",
  "IT": "Itália",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordânia",
  "JP": "Japão",
  "KE": "Quênia",
  "KG": "Quirguistão",
  "KH": "Camboja",
  "KI": "Quiribati",
  "KM": "Comores",
  "KN": "São Cristóvão e Névis",
  "KP": "Coreia do Norte",
  "KR": "Coreia do Sul",
  "KW": "Kuwait",
  "KY": "Ilhas Cayman",
  "KZ": "Cazaquistão",
  "LA": "Laos",
  "LB": "Líbano",
  "LC": "Santa Lúcia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Libéria",
  "LS": "Lesoto",
  "LT": "Lituânia",
  "LU": "Luxemburgo",
  "LV": "Letônia",
  "LY": "Líbia",
  "MA": "Marrocos",
  "MC": "Mônaco",
  "MD": "Moldávia",
  "ME": "Montenegro",
  "MF": "São Martinho",
  "MG": "Madagascar",
  "MH": "Ilhas Marshall",
  "MK": "Macedônia do Norte",
  "ML": "Mali",
  "MM": "Mianmar (Birmânia)",
  "MN": "Mongólia",
  "MO": "Macau, RAE da China",
  "MP": "Ilhas Marianas do Norte",
  "MQ": "Martinica",
  "MR": "Mauritânia",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Maurício",
  "MV": "Maldivas",
  "MW": "Malaui",
  "MX": "México",
  "MY": "Malásia",
  "MZ": "Moçambique",
  "NA": "Namíbia",
  "NC": "Nova Caledônia",
  "NE": "Níger",
  "NF": "Ilha Norfolk",
  "NG": "Nigéria",
  "NI": "Nicarágua",
  "NL": "Países Baixos",
  "NO": "Noruega",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Nova Zelândia",
  "OM": "Omã",
  "PA": "Panamá",
  "PE": "Peru",
  "PF": "Polinésia Francesa",
  "PG": "Papua-Nova Guiné",
  "PH": "Filipinas",
  "PK": "Paquistão",
  "PL": "Polônia",
  "PM": "São Pedro e Miquelão",
  "PR": "Porto Rico",
  "PS": "Territórios palestinos",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguai",
  "QA": "Catar",
  "RE": "Reunião",
  "RO": "Romênia",
  "RS": "Sérvia",
  "RU": "Rússia",
  "RW": "Ruanda",
  "SA": "Arábia Saudita",
  "SB": "Ilhas Salomão",
  "SC": "Seicheles",
  "SD": "Sudão",
  "SE": "Suécia",
  "SG": "Singapura",
  "SH": "Santa Helena",
  "SI": "Eslovênia",
  "SJ": "Svalbard e Jan Mayen",
  "SK": "Eslováquia",
  "SL": "Serra Leoa",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somália",
  "SR": "Suriname",
  "SS": "Sudão do Sul",
  "ST": "São Tomé e Príncipe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Síria",
  "SZ": "Essuatíni",
  "TA": "Tristão da Cunha",
  "TC": "Ilhas Turcas e Caicos",
  "TD": "Chade",
  "TG": "Togo",
  "TH": "Tailândia",
  "TJ": "Tadjiquistão",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turcomenistão",
  "TN": "Tunísia",
  "TO": "Tonga",
  "TR": "Turquia",
  "TT": "Trinidad e Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzânia",
  "UA": "Ucrânia",
  "UG": "Uganda",
  "US": "Estados Unidos",
  "UY": "Uruguai",
  "UZ": "Uzbequistão",
  "VA": "Cidade do Vaticano",
  "VC": "São Vicente e Granadinas",
  "VE": "Venezuela",
  "VG": "Ilhas Virgens Britânicas",
  "VI": "Ilhas Virgens Americanas",
  "VN": "Vietnã",
  "VU": "Vanuatu",
  "WF": "Wallis e Futuna",
  "WS": "Samoa",
  "XK": "Kosovo",
  "YE": "Iêmen",
  "YT": "Mayotte",
  "ZA": "África do Sul",
  "ZM": "Zâmbia",
  "ZW": "Zimbábue"
 },
 "ru": {
  "AC": "о-в Вознесения",
  "AD": "Андорра",
  "AE": "ОАЭ",
  "AF": "Афганистан",
  "AG": "Антигуа и Барбуда",
  "AI": "Ангилья",
  "AL": "Албания",
  "AM": "Армения",
  "AO": "Ангола",
  "AR": "Аргентина",
  "AS": "Американское Самоа",
  "AT": "Австрия",
  "AU": "Австралия",
  "AW": "Аруба",
  "AX": "Аландские о-ва",
  "AZ": "Азербайджан",
  "BA": "Босния и Герцеговина",
  "BB": "Барбадос",
  "BD": "Бангладеш",
  "BE": "Бельгия",
  "BF": "Буркина-Фасо",
  "BG": "Болгария",
  "BH": "Бахрейн",
  "BI": "Бурунди",
  "BJ": "Бенин",
  "BL": "Сен-Бартелеми",
  "BM": "Бермудские о-ва",
  "BN": "Бруней",
  "BO": "Боливия",
  "BQ": "Бонэйр, Синт-Эстатиус и Саба",
  "BR": "Бразилия",
  "BS": "Багамы",
  "BT": "Бутан",
  "BW": "Ботсвана",
  "BY": "Беларусь",
  "BZ": "Белиз",
  "CA": "Канада",
  "CC": "Кокосовые о-ва",
  "CD": "Конго - Киншаса",
  "CF": "Центрально-Африканская Республика",
  "CG": "Конго - Браззавиль",
  "CH": "Швейцария",
  "CI": "Кот-д’Ивуар",
  "CK": "о-ва Кука",
  "CL": "Чили",
  "CM": "Камерун",
  "CN": "Китай",
  "CO": "Колумбия",
  "CR": "Коста-Рика",
  "CU": "Куба",
  "CV": "Кабо-Верде",
  "CW": "Кюрасао",
  "CX": "о-в Рождества",
  "CY": "Кипр",
  "CZ": "Чехия",
  "DE": "Германия",
  "DJ": "Джибути",
  "DK": "Дания",
  "DM": "Доминика",
  "DO": "Доминиканская Республика",
  "DZ": "Алжир",
  "EC": "Эквадор",
  "EE": "Эстония",
  "EG": "Египет",
  "EH": "Западная Сахара",
  "ER": "Эритрея",
  "ES": "Испания",
  "ET": "Эфиопия",
  "FI": "Финляндия",
  "FJ": "Фиджи",
  "FK": "Фолклендские о-ва",
  "FM": "Федеративные Штаты Микронезии",
  "FO": "Фарерские о-ва",
  "FR": "Франция",
  "GA": "Габон",
  "GB": "Великобритания",
  "GD": "Гренада",
  "GE": "Грузия",
  "GF": "Французская Гвиана",
  "GG": "Гернси",
  "GH": "Гана",
  "GI": "Гибралтар",
  "GL": "Гренландия",
  "GM": "Гамбия",
  "GN": "Гвинея",
  "GP": "Гваделупа",
  "GQ": "Экваториальная Гвинея",
  "GR": "Греция",
  "GT": "Гватемала",
  "GU": "Гуам",
  "GW": "Гвинея-Бисау",
  "GY": "Гайана",
  "HK": "Гонконг (САР)",
  "HN": "Гондурас",
  "HR": "Хорватия",
  "HT": "Гаити",
  "HU": "Венгрия",
  "ID": "Индонезия",
  "IE": "Ирландия",
  "IL": "Израиль",
  "IM": "о-в Мэн",
  "IN": "Индия",
  "IO": "Британская территория в Индийском океане",
  "IQ": "Ирак",
  "IR": "Иран",
  "IS": "Исландия",
  "IT": "Италия",
  "JE": "Джерси",
  "JM": "Ямайка",
  "JO": "Иордания",
  "JP": "Япония",
  "KE": "Кения",
  "KG": "Киргизия",
  "KH": "Камбоджа",
  "KI": "Кирибати",
  "KM": "Коморы",
  "KN": "Сент-Китс и Невис",
  "KP": "КНДР",
  "KR": "Республика Корея",
  "KW": "Кувейт",
  "KY": "о-ва Кайман",
  "KZ": "Казахстан",
  "LA": "Лаос",
  "LB": "Ливан",
  "LC": "Сент-Люсия",
  "LI": "Лихтенштейн",
  "LK": "Шри-Ланка",
  "LR": "Либерия",
  "LS": "Лесото",
  "LT": "Литва",
  "LU": "Люксембург",
  "LV": "Латвия",
  "LY": "Ливия",
  "MA": "Марокко",
  "MC": "Монако",
  "MD": "Молдова",
  "ME": "Черногория",
  "MF": "Сен-Мартен",
  "MG": "Мадагаскар",
  "MH": "Маршалловы о-ва",
  "MK": "Северная Македония",
  "ML": "Мали",
  "MM": "Мьянма (Бирма)",
  "MN": "Монголия",
  "MO": "Макао (САР)",
  "MP": "Северные Марианские о-ва",
  "MQ": "Мартиника",
  "MR": "Мавритания",
  "MS": "Монтсеррат",
  "MT": "Мальта",
  "MU": "Маврикий",
  "MV": "Мальдивы",
  "MW": "Малави",
  "MX": "Мексика",
  "MY": "Малайзия",
  "MZ": "Мозамбик",
  "NA": "Намибия",
  "NC": "Новая Каледония",
  "NE": "Нигер",
  "NF": "о-в Норфолк",
  "NG": "Нигерия",
  "NI": "Никарагуа",
  "NL": "Нидерланды",
  "NO": "Норвегия",
  "NP": "Непал",
  "NR": "Науру",
  "NU": "Ниуэ",
  "NZ": "Новая Зеландия",
  "OM": "Оман",
  "PA": "Панама",
  "PE": "Перу",
  "PF": "Французская Полинезия",
  "PG": "Папуа — Новая Гвинея",
  "PH": "Филиппины",
  "PK": "Пакистан",
  "PL": "Польша",
  "PM": "Сен-Пьер и Микелон",
  "PR": "Пуэрто-Рико",
  "PS": "Палестинские территории",
  "PT": "Португалия",
  "PW": "Палау",
  "PY": "Парагвай",
  "QA": "Катар",
  "RE": "Реюньон",
  "RO": "Румыния",
  "RS": "Сербия",
  "RU": "Россия",
  "RW": "Руанда",
  "SA": "Саудовская Аравия",
  "SB": "Соломоновы о-ва",
  "SC": "Сейшельские о-ва",
  "SD": "Судан",
  "SE": "Швеция",
  "SG": "Сингапур",
  "SH": "о-в Св. Елены",
  "SI": "Словения",
  "SJ": "Шпицберген и Ян-Майен",
  "SK": "Словакия",
  "SL": "Сьерра-Леоне",
  "SM": "Сан-Марино",
  "SN": "Сенегал",
  "SO": "Сомали",
  "SR": "Суринам",
  "SS": "Южный Судан",
  "ST": "Сан-Томе и Принсипи",
  "SV": "Сальвадор",
  "SX": "Синт-Мартен",
  "SY": "Сирия",
  "SZ": "Эсватини",
  "TA": "Тристан-да-Кунья",
  "TC": "Тёркс и Кайкос",
  "TD": "Чад",
  "TG": "Того",
  "TH": "Таиланд",
  "TJ": "Таджикистан",
  "TK": "Токелау",
  "TL": "Восточный Тимор",
  "TM": "Туркменистан",
  "TN": "Тунис",
  "TO": "Тонга",
  "TR": "Турция",
  "TT": "Тринидад и Тобаго",
  "TV": "Тувалу",
  "TW": "Тайвань",
  "TZ": "Танзания",
  "UA": "Украина",
  "UG": "Уганда",
  "US": "Соединенные Штаты",
  "UY": "Уругвай",
  "UZ": "Узбекистан",
  "VA": "Ватикан",
  "VC": "Сент-Винсент и Гренадины",
  "VE": "Венесуэла",
  "VG": "Виргинские о-ва (Великобритания)",
  "VI": "Виргинские о-ва (США)",
  "VN": "Вьетнам",
  "VU": "Вануату",
  "WF": "Уоллис и Футуна",
  "WS": "Самоа",
  "XK": "Косово",
  "YE": "Йемен",
  "YT": "Майотта",
  "ZA": "Южно-Африканская Республика",
  "ZM": "Замбия",
  "ZW": "Зимбабве"
 },
 "zh": {
  "AC": "阿森松岛",
  "AD": "安道尔",
  "AE": "阿拉伯联合酋长国",
  "AF": "阿富汗",
  "AG": "安提瓜和巴布达",
  "AI": "安圭拉",
  "AL": "阿尔巴尼亚",
  "AM": "亚美尼亚",
  "AO": "安哥拉",
  "AR": "阿根廷",
  "AS": "美属萨摩亚",
  "AT": "奥地利",
  "AU": "澳大利亚",
  "AW": "阿鲁巴",
  "AX": "奥兰群岛",
  "AZ": "阿塞拜疆",
  "BA": "波斯尼亚和黑塞哥维那",
  "BB": "巴巴多斯",
  "BD": "孟加拉国",
  "BE": "比利时",
  "BF": "布基纳法索",
  "BG": "保加利亚",
  "BH": "巴林",
  "BI": "布隆迪",
  "BJ": "贝宁",
  "BL": "圣巴泰勒米",
  "BM": "百慕大",
  "BN": "文莱",
  "BO": "玻利维亚",
  "BQ": "荷属加勒比区",
  "BR": "巴西",
  "BS": "巴哈马",
  "BT": "不丹",
  "BW": "博茨瓦纳",
  "BY": "白俄罗斯",
  "BZ": "伯利兹",
  "CA": "加拿大",
  "CC": "科科斯（基林）群岛",
  "CD": "刚果（金）",
  "CF": "中非共和国",
  "CG": "刚果（布）",
  "CH": "瑞士",
  "CI": "科特迪瓦",
  "CK": "库克群岛",
  "CL": "智利",
  "CM": "喀麦隆",
  "CN": "中国",
  "CO": "哥伦比亚",
  "CR": "哥斯达黎加",
  "CU": "古巴",
  "CV": "佛得角",
  "CW": "库拉索",
  "CX": "圣诞岛",
  "CY": "塞浦路斯",
  "CZ": "捷克",
  "DE": "德国",
  "DJ": "吉布提",
  "DK": "丹麦",
  "DM": "多米尼克",
  "DO": "多米尼加共和国",
  "DZ": "阿尔及利亚",
  "EC": "厄瓜多尔",
  "EE": "爱沙尼亚",
  "EG": "埃及",
  "EH": "西撒哈拉",
  "ER": "厄立特里亚",
  "ES": "西班牙",
  "ET": "埃塞俄比亚",
  "FI": "芬兰",
  "FJ": "斐济",
  "FK": "福克兰群岛",
  "FM": "密克罗尼西亚",
  "FO": "法罗群岛",
  "FR": "法国",
  "GA": "加蓬",
  "GB": "英国",
  "GD": "格林纳达",
  "GE": "格鲁吉亚",
  "GF": "法属圭亚那",
  "GG": "根西岛",
  "GH": "加纳",
  "GI": "直布罗陀",
  "GL": "格陵兰",
  "GM": "冈比亚",
  "GN": "几内亚",
  "GP": "瓜德罗普",
  "GQ": "赤道几内亚",
  "GR": "希腊",
  "GT": "危地马拉",
  "GU": "关岛",
  "GW": "几内亚比绍",
  "GY": "圭亚那",
  "HK": "中国香港特别行政区",
  "HN": "洪都拉斯",
  "HR": "克罗地亚",
  "HT": "海地",
  "HU": "匈牙利",
  "ID": "印度尼西亚",
  "IE": "爱尔兰",
  "IL": "以色列",
  "IM": "马恩岛",
  "IN": "印度",
  "IO": "英属印度洋领地",
  "IQ": "伊拉克",
  "IR": "伊朗",
  "IS": "冰岛",
  "IT": "意大利",
  "JE": "泽西岛",
  "JM": "牙买加",
  "JO": "约旦",
  "JP": "日本",
  "KE": "肯尼亚",
  "KG": "吉尔吉斯斯坦",
  "KH": "柬埔寨",
  "KI": "基里巴斯",
  "KM": "科摩罗",
  "KN": "圣基茨和尼维斯",
  "KP": "朝鲜",
  "KR": "韩国",
  "KW": "科威特",
  "KY": "开曼群岛",
  "KZ": "哈萨克斯坦",
  "LA": "老挝",
  "LB": "黎巴嫩",
  "LC": "圣卢西亚",
  "LI": "列支敦士登",
  "LK": "斯里兰卡",
  "LR": "利比里亚",
  "LS": "莱索托",
  "LT": "立陶宛",
  "LU": "卢森堡",
  "LV": "拉脱维亚",
  "LY": "利比亚",
  "MA": "摩洛哥",
  "MC": "摩纳哥",
  "MD": "摩尔多瓦",
  "ME": "黑山",
  "MF": "法属圣马丁",
  "MG": "马达加斯加",
  "MH": "马绍尔群岛",
  "MK": "北马其顿",
  "ML": "马里",
  "MM": "缅甸",
  "MN": "蒙古",
  "MO": "中国澳门特别行政区",
  "MP": "北马里亚纳群岛",
  "MQ": "马提尼克",
  "MR": "毛里塔尼亚",
  "MS": "蒙特塞拉特",
  "MT": "马耳他",
  "MU": "毛里求斯",
  "MV": "马尔代夫",
  "MW": "马拉维",
  "MX": "墨西哥",
  "MY": "马来西亚",
  "MZ": "莫桑比克",
  "NA": "纳米比亚",
  "NC": "新喀里多尼亚",
  "NE": "尼日尔",
  "NF": "诺福克岛",
  "NG": "尼日利亚",
  "NI": "尼加拉瓜",
  "NL": "荷兰",
  "NO": "挪威",
  "NP": "尼泊尔",
  "NR": "瑙鲁",
  "NU": "纽埃",
  "NZ": "新西兰",
  "OM": "阿曼",
  "PA": "巴拿马",
  "PE": "秘鲁",
  "PF": "法属波利尼西亚",
  "PG": "巴布亚新几内亚",
  "PH": "菲律宾",
  "PK": "巴基斯坦",
  "PL": "波兰",
  "PM": "圣皮埃尔和密克隆群岛",
  "PR": "波多黎各",
  "PS": "巴勒斯坦领土",
  "PT": "葡萄牙",
  "PW": "帕劳",
  "PY": "巴拉圭",
  "QA": "卡塔尔",
  "RE": "留尼汪",
  "RO": "罗马尼亚",
  "RS": "塞尔维亚",
  "RU": "俄罗斯",
  "RW": "卢旺达",
  "SA": "沙特阿拉伯",
  "SB": "所罗门群岛",
  "SC": "塞舌尔",
  "SD": "苏丹",
  "SE": "瑞典",
  "SG": "新加坡",
  "SH": "圣赫勒拿",
  "SI": "斯洛文尼亚",
  "SJ": "斯瓦尔巴和扬马延",
  "SK": "斯洛伐克",
  "SL": "塞拉利昂",
  "SM": "圣马力诺",
  "SN": "塞内加尔",
  "SO": "索马里",
  "SR": "苏里南",
  "SS": "南苏丹",
  "ST": "圣多美和普林西比",
  "SV": "萨尔瓦多",
  "SX": "荷属圣马丁",
  "SY": "叙利亚",
  "SZ": "斯威士兰",
  "TA": "特里斯坦-达库尼亚群岛",
  "TC": "特克斯和凯科斯群岛",
  "TD": "乍得",
  "TG": "多哥",
  "TH": "泰国",
  "TJ": "塔吉克斯坦",
  "TK": "托克劳",
  "TL": "东帝汶",
  "TM": "土库曼斯坦",
  "TN": "突尼斯",
  "TO": "汤加",
  "TR": "土耳其",
  "TT": "特立尼达和多巴哥",
  "TV": "图瓦卢",
  "TW": "台湾",
  "TZ": "坦桑尼亚",
  "UA": "乌克兰",
  "UG": "乌干达",
  "US": "美国",
  "UY": "乌拉圭",
  "UZ": "乌兹别克斯坦",
  "VA": "梵蒂冈",
  "VC": "圣文森特和格林纳丁斯",
  "VE": "委内瑞拉",
  "VG": "英属维尔京群岛",
  "VI": "美属维尔京群岛",
  "VN": "越南",
  "VU": "瓦努阿图",
  "WF": "瓦利斯和富图纳",
  "WS": "萨摩亚",
  "XK": "科索沃",
  "YE": "也门",
  "YT": "马约特",
  "ZA": "南非",
  "ZM": "赞比亚",
  "ZW": "津巴布韦"
 }
};

export default COUNTRY_NAMES;
